const mimeTypes = {
  text: "text/plain",
  html: "text/html", 
  css: "text/css",
  csv: "text/csv",
  ics: "text/calendar",
  png: "image/png",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  gif: "image/gif",
  svg: "image/svg+xml",
  webp: "image/webp",
  tiff: "image/tiff",
  tif: "image/tiff",
  mp4: "video/mp4",
  webm: "video/webm",
  ogg: "video/ogg",
  mpeg: "video/mpeg",
  mov: "video/quicktime",
  mp3: "audio/mpeg",
  wav: "audio/wav",
  mid: "audio/midi",
  midi: "audio/midi",
  woff: "application/woff",
  woff2: "application/woff2",
  eot: "application/vnd.ms-fontobject",
  zip: "application/zip",
  gz: "application/gzip",
  tar: "application/x-tar",
  rar: "application/x-rar-compressed",
  "7z": "x-7z-compressed",
   "3mf": "model/3mf",
   gltf: "model/gltf+json",
   glb: "model/gltf-binary",
  js: "application/javascript",
  json: "application/json",
  xml: "application/xml",
  xhtml: "application/xhtml+xml",
  pdf: "application/pdf",
  sql: "application/sql",
  rdf: "application/rdf",
  rss: "application/rss",
  jsonld: "application/ld+json"
}

module.exports = mimeTypes;